// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using NetEaseJsonData.Repository;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace NetEaseJsonData.Repository
{
    internal class Artist
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("picUrl")]
        public object PicUrl { get; set; }

        [JsonProperty("alias")]
        public object[] Alias { get; set; }

        [JsonProperty("albumSize")]
        public int AlbumSize { get; set; }

        [JsonProperty("picId")]
        public int PicId { get; set; }

        [JsonProperty("img1v1Url")]
        public string Img1v1Url { get; set; }

        [JsonProperty("img1v1")]
        public int Img1v1 { get; set; }

        [JsonProperty("trans")]
        public object Trans { get; set; }
    }
    internal class Album
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("size")]
        public int Size { get; set; }

        [JsonProperty("picId")]
        public object PicId { get; set; }

        [JsonProperty("blurPicUrl")]
        public string BlurPicUrl { get; set; }

        [JsonProperty("companyId")]
        public int CompanyId { get; set; }

        [JsonProperty("pic")]
        public object Pic { get; set; }

        [JsonProperty("picUrl")]
        public string PicUrl { get; set; }

        [JsonProperty("publishTime")]
        public object PublishTime { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("tags")]
        public string Tags { get; set; }

        [JsonProperty("company")]
        public string Company { get; set; }

        [JsonProperty("briefDesc")]
        public string BriefDesc { get; set; }

        [JsonProperty("artist")]
        public Artist Artist { get; set; }

        [JsonProperty("songs")]
        public object[] Songs { get; set; }

        [JsonProperty("alias")]
        public object[] Alias { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("copyrightId")]
        public int CopyrightId { get; set; }

        [JsonProperty("commentThreadId")]
        public string CommentThreadId { get; set; }

        [JsonProperty("artists")]
        public Artist[] Artists { get; set; }

        [JsonProperty("subType")]
        public string SubType { get; set; }
    }
    internal class Song
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("position")]
        public int Position { get; set; }

        [JsonProperty("alias")]
        public string[] Alias { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("fee")]
        public int Fee { get; set; }

        [JsonProperty("copyrightId")]
        public int CopyrightId { get; set; }

        [JsonProperty("disc")]
        public string Disc { get; set; }

        [JsonProperty("no")]
        public int No { get; set; }

        [JsonProperty("artists")]
        public Artist[] Artists { get; set; }

        [JsonProperty("album")]
        public Album Album { get; set; }

        [JsonProperty("starred")]
        public bool Starred { get; set; }

        [JsonProperty("popularity")]
        public double Popularity { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("starredNum")]
        public int StarredNum { get; set; }

        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonProperty("playedNum")]
        public int PlayedNum { get; set; }

        [JsonProperty("dayPlays")]
        public int DayPlays { get; set; }

        [JsonProperty("hearTime")]
        public int HearTime { get; set; }

        [JsonProperty("ringtone")]
        public string Ringtone { get; set; }

        [JsonProperty("crbt")]
        public object Crbt { get; set; }

        [JsonProperty("audition")]
        public object Audition { get; set; }

        [JsonProperty("copyFrom")]
        public string CopyFrom { get; set; }

        [JsonProperty("commentThreadId")]
        public string CommentThreadId { get; set; }

        [JsonProperty("rtUrl")]
        public object RtUrl { get; set; }

        [JsonProperty("ftype")]
        public int Ftype { get; set; }

        [JsonProperty("rtUrls")]
        public object[] RtUrls { get; set; }

        [JsonProperty("copyright")]
        public int Copyright { get; set; }

        [JsonProperty("rtype")]
        public int Rtype { get; set; }

        [JsonProperty("rurl")]
        public object Rurl { get; set; }

        [JsonProperty("mvid")]
        public int Mvid { get; set; }

        [JsonProperty("bMusic")]
        public Music BMusic { get; set; }

        [JsonProperty("mp3Url")]
        public string Mp3Url { get; set; }

        [JsonProperty("hMusic")]
        public Music HMusic { get; set; }

        [JsonProperty("mMusic")]
        public Music MMusic { get; set; }

        [JsonProperty("lMusic")]
        public Music LMusic { get; set; }

        [JsonProperty("rUrl")]
        public object RUrl { get; set; }
    }
    internal class Music
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("size")]
        public int Size { get; set; }

        [JsonProperty("extension")]
        public string Extension { get; set; }

        [JsonProperty("sr")]
        public int Sr { get; set; }

        [JsonProperty("dfsId")]
        public object DfsId { get; set; }

        [JsonProperty("bitrate")]
        public int Bitrate { get; set; }

        [JsonProperty("playTime")]
        public int PlayTime { get; set; }

        [JsonProperty("volumeDelta")]
        public double VolumeDelta { get; set; }
    }
    internal class Result
    {

        [JsonProperty("songs")]
        public Song[] Songs { get; set; }

        [JsonProperty("songCount")]
        public int SongCount { get; set; }
    }
    internal class Lrc
    {

        [JsonProperty("version")]
        public int Version { get; set; }

        [JsonProperty("lyric")]
        public string Lyric { get; set; }
    }
    internal class Klyric
    {

        [JsonProperty("version")]
        public int Version { get; set; }
    }
    internal class Tlyric
    {

        [JsonProperty("version")]
        public int Version { get; set; }

        [JsonProperty("lyric")]
        public object Lyric { get; set; }
    }
}

namespace ProjectMato.iOS
{

    internal class MusicListData
    {

        [JsonProperty("result")]
        public Result Result { get; set; }

        [JsonProperty("code")]
        public int Code { get; set; }
    }


    internal class MusicDetailData
    {

        [JsonProperty("songs")]
        public Song[] Songs { get; set; }


        [JsonProperty("code")]
        public int Code { get; set; }
    }

    internal class LrcData
    {

        [JsonProperty("sgc")]
        public bool Sgc { get; set; }

        [JsonProperty("sfy")]
        public bool Sfy { get; set; }

        [JsonProperty("qfy")]
        public bool Qfy { get; set; }

        [JsonProperty("lrc")]
        public Lrc Lrc { get; set; }

        [JsonProperty("klyric")]
        public Klyric Klyric { get; set; }

        [JsonProperty("tlyric")]
        public Tlyric Tlyric { get; set; }

        [JsonProperty("code")]
        public int Code { get; set; }
    }

}


